nodeLinker: node-modules

packageExtensions:
  "@mui/x-data-grid@*":
    peerDependencies:
      "@mui/system": "*"
  "@mui/x-date-pickers@*":
    peerDependencies:
      "@mui/system": "*"
  "@mui/x-tree-view@*":
    peerDependencies:
      "@mui/system": "*"
  "@tiptap/react@*":
    peerDependencies:
      "@tiptap/core": "*"
  "@tiptap/extension-bubble-menu@*":
    peerDependencies:
      "@tiptap/core": "*"
  "@tiptap/extension-text-align@*":
    peerDependencies:
      "@tiptap/core": "*"
  "@tiptap/extension-image@*":
    peerDependencies:
      "@tiptap/core": "*"
  "@tiptap/extensions@*":
    peerDependencies:
      "@tiptap/core": "*"
  "@tiptap/extension-code-block-lowlight@*":
    peerDependencies:
      "@tiptap/core": "*"
      "@tiptap/extension-code-block": "*"
      "highlight.js": "*"
